// Example of an Auth Action File
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const BEGIN_AUTH = 'BEGIN_AUTH';
export const END_AUTH = 'END_AUTH';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

// COMMON REDUCER
export const COMMON_CHANGE_GREETING = 'COMMON_CHANGE_GREETING';

